name: Maintenance

on:
  schedule:
    # Run every Monday at 9 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch:

jobs:
  security-audit:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'yarn'
        
    - name: Install dependencies
      run: yarn install --frozen-lockfile
      
    - name: Run security audit
      run: yarn audit --audit-level high
      
    - name: Check for outdated packages
      run: yarn outdated || true
      
    - name: Create issue on security vulnerabilities
      if: failure()
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: '🔒 Security vulnerabilities detected',
            body: `Security audit failed on ${new Date().toISOString().split('T')[0]}. Please review and update dependencies.`,
            labels: ['security', 'dependencies']
          })

  dependency-update:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'yarn'
        
    - name: Update dependencies
      run: |
        yarn upgrade --latest
        
    - name: Run tests after update
      run: |
        yarn install
        yarn type-check
        yarn test
        yarn build
        
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'chore: update dependencies'
        title: '🔄 Automated dependency updates'
        body: |
          This PR contains automated dependency updates.
          
          - All dependencies have been updated to their latest versions
          - Tests have been run to ensure compatibility
          - Please review changes before merging
          
          Generated by GitHub Actions on ${{ github.run_id }}
        branch: automated-dependency-updates
        delete-branch: true
        labels: |
          dependencies
          automated