name: Release

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., v1.0.0)'
        required: true
        type: string

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  release:
    runs-on: ${{ matrix.os }}
    
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-latest
            platform: mac
            cache_key: macos
          - os: windows-latest
            platform: win
            cache_key: windows
          - os: ubuntu-latest
            platform: linux
            cache_key: linux
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22.x'
        cache: 'yarn'
        
    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      shell: bash
      run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT
      
    - name: Cache yarn dependencies
      uses: actions/cache@v4
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
        
    - name: Cache Electron
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/electron
          ~/Library/Caches/electron
          %LOCALAPPDATA%\electron\Cache
        key: ${{ runner.os }}-electron-${{ hashFiles('**/package.json') }}
        restore-keys: |
          ${{ runner.os }}-electron-
        
    - name: Install dependencies
      run: yarn install --frozen-lockfile
      
    - name: Run tests
      run: |
        yarn type-check
        yarn test
        
    - name: Build application
      run: yarn build
      
    # Platform-specific builds
    - name: Build for macOS
      if: matrix.platform == 'mac'
      run: yarn dist:mac
      env:
        CSC_IDENTITY_AUTO_DISCOVERY: false
        DEBUG: electron-builder
        
    - name: Build for Windows
      if: matrix.platform == 'win'
      run: yarn dist:win
      env:
        DEBUG: electron-builder
        
    - name: Build for Linux
      if: matrix.platform == 'linux'
      run: yarn dist:linux
      env:
        DEBUG: electron-builder
      
    - name: List build outputs
      shell: bash
      run: |
        echo "Build outputs:"
        ls -la release/ || echo "No release directory found"
        
    # Upload artifacts to GitHub Release
    - name: Upload Release Assets
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          release/*.dmg
          release/*.zip
          release/*.exe
          release/*.AppImage
          release/*.deb
          release/*.rpm
          release/*.blockmap
          release/latest*.yml
        draft: true
        prerelease: ${{ contains(github.ref, 'beta') || contains(github.ref, 'alpha') || contains(github.ref, 'rc') }}
        generate_release_notes: true
        fail_on_unmatched_files: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: release-${{ matrix.platform }}
        path: release/
        retention-days: 30
        if-no-files-found: warn

  # Auto-updater files
  publish-updates:
    needs: release
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts/
        merge-multiple: true
        
    - name: Prepare update files
      run: |
        mkdir -p updates
        find artifacts/ -name "latest*.yml" -exec cp {} updates/ \; || echo "No update files found"
        find artifacts/ -name "*.blockmap" -exec cp {} updates/ \; || echo "No blockmap files found"
        ls -la updates/ || echo "No updates directory"
        
    - name: Upload update metadata
      uses: softprops/action-gh-release@v2
      with:
        files: updates/*
        tag_name: ${{ github.ref_name }}
        fail_on_unmatched_files: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}